export async function GET() {

       const words = [
       	     { "key": "1", "word": "velo", "translation": "自転車"},
       	     { "key": "2", "word": "duex", "translation": "2"},
       	     { "key": "3", "word": "la serviette", "translation": "ナプキン"},	
       	     { "key": "4", "word": "miam", "translation": "おいしそう"},
       	     { "key": "5", "word": "verre", "translation": "グラス"},
       	     { "key": "6", "word": "trois", "translation": "3"},
       	     { "key": "7", "word": "aujourd'hui", "translation": "今日"},
       	     { "key": "8", "word": "placard", "translation": "戸棚"},
       	     { "key": "9", "word": "gâteau", "translation": "ケーキ"},
       	     { "key": "10", "word": "quatre", "translation": "4"},
       	     { "key": "11", "word": "ouvert", "translation": "開いている"},
       	     { "key": "12", "word": "tasse", "translation": "カップ"},
       	     { "key": "13", "word": "cadeau", "translation": "プレゼント"},
       	     { "key": "14", "word": "cinq", "translation": "5"},
       	     { "key": "15", "word": "maintenant", "translation": "今"},
       	     { "key": "16", "word": "De rien", "translation": "どういたしまして"},
       	     { "key": "17", "word": "quand", "translation": "いつ"},
       	     { "key": "18", "word": "près d'ici", "translation": "この近く"},
	     
       	     { "key": "19", "word": "la boulangerie", "translation": "パン屋"},
       	     { "key": "20", "word": "la banque", "translation": "銀行"},
       	     { "key": "21", "word": "l'appartement", "translation": "アパート"},
       	     { "key": "22", "word": "le jardin", "translation": "庭"},
       	     { "key": "23", "word": "la musique", "translation": "音楽"},
       	     { "key": "24", "word": "chocolat", "translation": "チョコレート"},
       	     { "key": "25", "word": "une ècole", "translation": "学校"},
       	     { "key": "26", "word": "le parc", "translation": "公園"},
       	     { "key": "27", "word": "la voiture", "translation": "車"},
       	     { "key": "28", "word": "la valise", "translation": "スーツケース"},	     
       	     { "key": "29", "word": "un avion", "translation": "飛行機"},
       	     { "key": "30", "word": "l'aèroport", "translation": "空港"},
       	     { "key": "31", "word": "le train", "translation": "電車"},
       	     { "key": "32", "word": "un billet d'avion", "translation": "航空券"},
       	     { "key": "33", "word": "ici", "translation": "ここに"},
       	     { "key": "34", "word": "la chouette", "translation": "フクロウ"},
       	     { "key": "35", "word": "le animal de campagnie", "translation": "ペット"},
       	     { "key": "36", "word": "père", "translation": "父"},
       	     { "key": "37", "word": "mère", "translation": "母"},
       	     { "key": "38", "word": "frère", "translation": "兄"},
       	     { "key": "39", "word": "sœur", "translation": "姉"},
       	     { "key": "40", "word": "fils", "translation": "息子"},

	     { "key": "41", "word": "fille", "translation": "娘"},
	     { "key": "42", "word": "mari", "translation": "旦那さん"},
	     { "key": "43", "word": "femme", "translation": "奥さん"},
	     { "key": "44", "word": "oncle", "translation": "叔父"},
	     { "key": "45", "word": "tante", "translation": "叔母"},
	     { "key": "46", "word": "neveu", "translation": "甥"},
	     { "key": "47", "word": "nièce", "translation": "姪"},
	     { "key": "48", "word": "la famille", "translation": "家族"},	     	     
	     { "key": "49", "word": "etudiant", "translation": "学生"},
	     { "key": "50", "word": "la universite", "translation": "大学"},
	     { "key": "51", "word": "professeur", "translation": "教授"},
	     { "key": "52", "word": "la journaliste", "translation": "記者"},
	     { "key": "53", "word": "fatiguè", "translation": "疲れる"},
	     { "key": "54", "word": "attention", "translation": "気をつけて"},
	     { "key": "55", "word": "mètier", "translation": "職業"},
	     { "key": "56", "word": "le avocat", "translation": "弁護士"},
	     { "key": "57", "word": "l'hopital", "translation": "病院"},
	     { "key": "58", "word": "le docteur", "translation": "医者"},
	     { "key": "59", "word": "la ville", "translation": "都市"},
	     { "key": "60", "word": "le ingenièur", "translation": "エンジニア"},
	     { "key": "61", "word": "quelqu'un", "translation": "誰か"},
	     { "key": "62", "word": "em retard", "translation": "遅れて"},
	     { "key": "63", "word": "clé", "translation": "カギ"},
	     { "key": "64", "word": "la chaise", "translation": "いす"},
	     { "key": "65", "word": "salon", "translation": "リビング"},
	     { "key": "66", "word": "la chambre", "translation": "寝室"},
	     { "key": "67", "word": "la fete", "translation": "パーティ"},
	     { "key": "68", "word": "la porte", "translation": "ドア"},
	     { "key": "69", "word": "le magasin", "translation": "店"},
	     { "key": "70", "word": "la table", "translation": "テーブル"},
	     { "key": "71", "word": "la canapé", "translation": "ソファー"},
	     { "key": "72", "word": "pache", "translation": "ポケット"},
	     { "key": "73", "word": "méchant", "translation": "意地悪"},
	     { "key": "74", "word": "intéressant", "translation": "興味深い"},
	     { "key": "75", "word": "bureau", "translation": "オフィス"},
	     { "key": "76", "word": "copine", "translation": "彼女"},
	     { "key": "77", "word": "copain", "translation": "彼氏"},
	     { "key": "78", "word": "ou", "translation": "もしくは or"},
	     { "key": "79", "word": "et", "translation": "と and"},
	     { "key": "80", "word": "pitit", "translation": "小さい"}	     
	];

       return Response.json( words );
}
