export async function GET() {

       const words = [
       	     { "key": "1", "word": "la boulangerie", "translation": "パン屋"},
       	     { "key": "2", "word": "la banque", "translation": "銀行"},
       	     { "key": "3", "word": "l'appartement", "translation": "アパート"},
       	     { "key": "4", "word": "le jardin", "translation": "庭"},
       	     { "key": "5", "word": "la musique", "translation": "音楽"},
       	     { "key": "6", "word": "chocolat", "translation": "チョコレート"},
       	     { "key": "7", "word": "une ècole", "translation": "学校"},
       	     { "key": "8", "word": "le parc", "translation": "公園"},
       	     { "key": "9", "word": "la voiture", "translation": "車"},
       	     { "key": "10", "word": "la valise", "translation": "スーツケース"},	     
       	     { "key": "11", "word": "un avion", "translation": "飛行機"},
       	     { "key": "12", "word": "l'aèroport", "translation": "空港"},
       	     { "key": "13", "word": "le train", "translation": "電車"},
       	     { "key": "14", "word": "un billet d'avion", "translation": "航空券"},
       	     { "key": "15", "word": "ici", "translation": "ここに"},
       	     { "key": "16", "word": "la chouette", "translation": "フクロウ"},
       	     { "key": "17", "word": "le animal de campagnie", "translation": "ペット"},
       	     { "key": "18", "word": "père", "translation": "父"},
       	     { "key": "19", "word": "mère", "translation": "母"},
       	     { "key": "20", "word": "frère", "translation": "兄"},
       	     { "key": "21", "word": "sœur", "translation": "姉"},
       	     { "key": "22", "word": "fils", "translation": "息子"},
	     { "key": "23", "word": "fille", "translation": "娘"},
	     { "key": "24", "word": "mari", "translation": "旦那さん"},
	     { "key": "25", "word": "femme", "translation": "奥さん"},
	     { "key": "26", "word": "oncle", "translation": "叔父"},
	     { "key": "27", "word": "tante", "translation": "叔母"},
	     { "key": "28", "word": "neveu", "translation": "甥"},
	     { "key": "29", "word": "nièce", "translation": "姪"},
	     { "key": "30", "word": "la famille", "translation": "家族"},	     	     
	     { "key": "31", "word": "etudiant", "translation": "学生"},
	     { "key": "32", "word": "la universite", "translation": "大学"},
	     { "key": "33", "word": "professeur", "translation": "教授"},
	     { "key": "34", "word": "la journaliste", "translation": "記者"},
	     { "key": "35", "word": "fatiguè", "translation": "疲れる"},
	     { "key": "36", "word": "attention", "translation": "気をつけて"},
	     { "key": "37", "word": "mètier", "translation": "職業"},
	     { "key": "38", "word": "le avocat", "translation": "弁護士"},
	     { "key": "39", "word": "l'hopital", "translation": "病院"},
	     { "key": "40", "word": "le docteur", "translation": "医者"},
	     
	     { "key": "41", "word": "la ville", "translation": "都市"},
	     { "key": "42", "word": "le ingenièur", "translation": "エンジニア"},
	     { "key": "43", "word": "quelqu'un", "translation": "誰か"},

	     { "key": "62", "word": "em retard", "translation": "遅れて"},
	     { "key": "63", "word": "clé", "translation": "カギ"},
	     { "key": "64", "word": "la chaise", "translation": "いす"},
	     { "key": "65", "word": "salon", "translation": "リビング"},
	     { "key": "66", "word": "la chambre", "translation": "寝室"},
	     { "key": "67", "word": "la fete", "translation": "パーティ"},
	     { "key": "68", "word": "la porte", "translation": "ドア"},
	     { "key": "69", "word": "le magasin", "translation": "店"},
	     { "key": "70", "word": "la table", "translation": "テーブル"},
	     
	     { "key": "71", "word": "la canapé", "translation": "ソファー"},
	     { "key": "72", "word": "pache", "translation": "ポケット"},
	     { "key": "73", "word": "méchant", "translation": "意地悪"},
	     { "key": "74", "word": "intéressant", "translation": "興味深い"},
	     { "key": "75", "word": "bureau", "translation": "オフィス"},
	     { "key": "76", "word": "copine", "translation": "彼女"},
	     { "key": "77", "word": "copain", "translation": "彼氏"},
	     { "key": "78", "word": "ou", "translation": "もしくは (or)"},
	     { "key": "79", "word": "et", "translation": "と (and)"},
	     { "key": "80", "word": "pitit", "translation": "小さい"},
	     { "key": "81", "word": "le vendeur", "translation": "店員"},
	     { "key": "82", "word": "la vendeuse", "translation": "店員"},
	     { "key": "83", "word": "chauffeur", "translation": "運転手"},
	     { "key": "84", "word": "cassé", "translation": "壊れている"},
	     { "key": "85", "word": "pressé", "translation": "急いで"},
	     { "key": "86", "word": "sale", "translation": "汚い"},
	     { "key": "87", "word": "Ouf", "translation": "ふう"},
	     { "key": "88", "word": "stylo", "translation": "ペン"},
	     { "key": "89", "word": "Voilà 〜", "translation": "これが〜です"},
	     { "key": "90", "word": "repas", "translation": "食事"},
	     { "key": "91", "word": "la salade", "translation": "サラダ"},
	     { "key": "92", "word": "joli", "translation": "きれい"},
	     { "key": "93", "word": "ensemble", "translation": "一緒に"},
	     { "key": "94", "word": "le voisin", "translation": "隣人"},
	     { "key": "95", "word": "la voisine", "translation": "隣人"},
	     { "key": "96", "word": "le chef", "translation": "上司"},
	     { "key": "97", "word": "la cheffe", "translation": "上司"},
	     { "key": "98", "word": "réunion", "translation": "会議"},
	     { "key": "99", "word": "important", "translation": "大切"},
	     { "key": "100", "word": "intelligent", "translation": "賢い"},
	     { "key": "101", "word": "amusant", "translation": "面白い"},
	     { "key": "102", "word": "Bien Sùr", "translation": "もちろん"},
	     { "key": "103", "word": "la végétarienne", "translation": "ベジタリアン"},
	     { "key": "104", "word": "propre", "translation": "清潔な"},
	     { "key": "105", "word": "le livre", "translation": "本"},
	     { "key": "106", "word": "- viens de 〜", "translation": "〜出身です"},
	     { "key": "107", "word": "nom", "translation": "名前"},
	     { "key": "108", "word": "la gare", "translation": "駅"},
	     { "key": "109", "word": "rapide", "translation": "速い"},
	     { "key": "110", "word": "vite", "translation": "急いで"},
	     { "key": "111", "word": "sur (la table)", "translation": "(テーブルの)上"},
	     { "key": "112", "word": "portable", "translation": "携帯電話"},
	     { "key": "113", "word": "trop 〜", "translation": "〜すぎる"},
	     { "key": "114", "word": "grand/grande", "translation": "大きい"},
	     { "key": "115", "word": "mais", "translation": "しかし"},
	     { "key": "116", "word": "seul", "translation": "一人"},
	     { "key": "117", "word": "sac", "translation": "かばん"},
	     { "key": "118", "word": "pressé", "translation": "急ぐ"},
	     { "key": "119", "word": "billet", "translation": "チケット"},
	     { "key": "110", "word": "passeport", "translation": "パスポート"},	     
	     
       	     { "key": "1101", "word": "velo", "translation": "自転車"},
       	     { "key": "1102", "word": "duex", "translation": "2"},
       	     { "key": "1103", "word": "la serviette", "translation": "ナプキン"},	
       	     { "key": "1104", "word": "miam", "translation": "おいしそう"},
       	     { "key": "1105", "word": "verre", "translation": "グラス"},
       	     { "key": "1106", "word": "trois", "translation": "3"},
       	     { "key": "1107", "word": "aujourd'hui", "translation": "今日"},
       	     { "key": "1108", "word": "placard", "translation": "戸棚"},
       	     { "key": "1109", "word": "gâteau", "translation": "ケーキ"},
       	     { "key": "1110", "word": "quatre", "translation": "4"},
       	     { "key": "1111", "word": "ouvert", "translation": "開いている"},
       	     { "key": "1112", "word": "tasse", "translation": "カップ"},
       	     { "key": "1113", "word": "cadeau", "translation": "プレゼント"},
       	     { "key": "1114", "word": "cinq", "translation": "5"},
       	     { "key": "1115", "word": "maintenant", "translation": "今"},
       	     { "key": "1116", "word": "De rien", "translation": "どういたしまして"},
       	     { "key": "1117", "word": "quand", "translation": "いつ"},
       	     { "key": "1118", "word": "près d'ici", "translation": "この近く"}
	];

       return Response.json( words );
}
